[tasks.strip]
args = ["target/x86_64-unknown-linux-gnu/release/rpnc"]
command = "strip"

[tasks.std]
args = ["build", "--release", "--target", "x86_64-unknown-linux-gnu"]
command = "xargo"

[tasks.runonly]
command = "target/x86_64-unknown-linux-gnu/release/rpnc"

[tasks.build]
dependencies = [
  "std",
  "strip",
]

[tasks.run]
dependencies = [
  "build",
  "runonly",
]
